<Project>
  <PropertyGroup Condition="'$(Phase0ArtifactsRoot)' != ''">
    <BaseIntermediateOutputPath>$(Phase0ArtifactsRoot)\$(MSBuildProjectName)-obj\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    <BaseOutputPath>$(Phase0ArtifactsRoot)\$(MSBuildProjectName)-bin\</BaseOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(AquaFarmIsolatedBuild)' == 'true'">
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory).isolated-obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>
